name = "ajproduction"
main = ".open-next/worker.js"
compatibility_date = "2026-05-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "ajproduction"

[[d1_databases]]
binding = "DB"
database_name = "luxury-studio-db"
database_id = "a68d8f40-e3d2-45aa-92cb-049d74bdf73e"
